/**
 * Git hooks for defense-in-depth guard enforcement.
 *
 * Installs pre-commit hooks in the tyvi project's .git directory
 * to catch direct git binary usage (IDE, scripts) that bypasses
 * the shell function wrapper.
 *
 * @module
 */

import { exists } from "@std/fs";
import { join } from "@std/path";
import type { Devspace } from "../types/mod.ts";

/**
 * Generate a pre-commit hook script.
 *
 * The hook ensures commits to the tyvi project happen from the root
 * or via the tyvi wrapper (which sets TYVI_ALLOW_COMMIT).
 *
 * @returns Hook script content
 */
export function generateHook(hookType: "pre-commit"): string {
  switch (hookType) {
    case "pre-commit":
      return `#!/bin/sh
# tyvi git guard — pre-commit hook
# Ensures commits happen from project root or via tyvi wrapper.
# Auto-generated by tyvi. Do not edit manually.

TYVI_ROOT="$(git rev-parse --show-toplevel)"

# Allow if at tyvi root
[ "$PWD" = "$TYVI_ROOT" ] && exit 0

# Allow if TYVI_ALLOW_COMMIT is set (by tyvi wrapper)
[ -n "$TYVI_ALLOW_COMMIT" ] && exit 0

# Block
echo "Commit from $(pwd) not allowed." >&2
echo "" >&2
echo "Run git from project root:" >&2
echo "  cd $TYVI_ROOT" >&2
echo "  git commit ..." >&2
echo "" >&2
echo "Or use tyvi:" >&2
echo "  tyvi git commit ..." >&2

exit 1
`;
  }
}

/**
 * Check if git hooks are installed in the devspace.
 *
 * @param devspace - Devspace configuration
 * @returns Whether the pre-commit hook exists
 */
export async function hasHooks(devspace: Devspace): Promise<boolean> {
  const hookPath = join(devspace.rootPath, ".git", "hooks", "pre-commit");
  return await exists(hookPath);
}

/**
 * Install git hooks in the devspace's .git directory.
 *
 * Creates the hooks directory if needed and writes the pre-commit hook.
 * Existing hooks are backed up with a `.bak` extension.
 *
 * @param devspace - Devspace configuration
 */
export async function installHooks(devspace: Devspace): Promise<void> {
  const gitDir = join(devspace.rootPath, ".git");
  if (!await exists(gitDir)) {
    throw new Error(
      `No .git directory at ${devspace.rootPath}. Initialize git first.`,
    );
  }

  const hooksDir = join(gitDir, "hooks");
  await Deno.mkdir(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, "pre-commit");

  // Back up existing hook
  if (await exists(hookPath)) {
    const content = await Deno.readTextFile(hookPath);
    if (!content.includes("tyvi git guard")) {
      await Deno.writeTextFile(`${hookPath}.bak`, content);
    }
  }

  const content = generateHook("pre-commit");
  await Deno.writeTextFile(hookPath, content);

  // Make executable
  await Deno.chmod(hookPath, 0o755);
}

/**
 * Remove tyvi git hooks from the devspace.
 *
 * Restores backed-up hooks if they exist.
 *
 * @param devspace - Devspace configuration
 */
export async function removeHooks(devspace: Devspace): Promise<void> {
  const hookPath = join(devspace.rootPath, ".git", "hooks", "pre-commit");

  if (!await exists(hookPath)) return;

  const content = await Deno.readTextFile(hookPath);
  if (!content.includes("tyvi git guard")) return;

  // Restore backup if it exists
  const backupPath = `${hookPath}.bak`;
  if (await exists(backupPath)) {
    const backup = await Deno.readTextFile(backupPath);
    await Deno.writeTextFile(hookPath, backup);
    await Deno.remove(backupPath);
  } else {
    await Deno.remove(hookPath);
  }
}
